## General (model.py)

EDUCATION_COUNTS: 
  - 48
  - 24
  - 12
NUM_HOUSEHOLDS: 84
NUM_FIRMS:
  SMALL: 4
  MEDIUM: 2
  LARGE: 1

TOTAL_STEPS: 100

## Agent Specific (agents.py)

# Firms

EXPORT_QUANTITY: 54.34698795
IMPORT_QUANTITY: 85.82947173

VALUE_ADDED: 5
GOODS_INTERVAL: 1
WAGES_INTERVAL: 4

REQUIRED_EMPLOYEES:
  SMALL: 
    - 4
    - 2
    - 1
  MEDIUM: 
    - 8
    - 4
    - 2
  LARGE: 
    - 16
    - 8
    - 4
GOODS_PRODUCED: 273 # for now its 3.25 * [# of households]
FRIM_STARTING_MONEY:
  SMALL: 1000
  MEDIUM: 1000
  LARGE: 1000
FRIM_STARTING_GOODS:
  SMALL: 0
  MEDIUM: 0
  LARGE: 0
SHARE_OF_PRODUCTION_CAPACITY:
  - 0.54
  - 0.29
  - 0.17

# Bank

LOAN_TICKS: 8
MONTHLY_INTEREST_RATE: 0.005
COMPOUND_INTERVAL: 4
BANK_STARTING_MONEY: 500

# Household

RENT_INTERVAL: 4
MORTGAGE_INTERVAL: 4
UTILITIES_INTERVAL: 4
GOODS_INTERVAL: 1

HOUSE_COST: 360
RENT: 15
UTILITIES_COST: 3
MORTGAGE_COST: 30
WEEKLY_GOODS_CONSUMPTION: 3
WEEKLY_GOODS_CONSUMPTION_RANGE: 0.25
MONTHLY_MORTGAGE_RATE: 0.035

HOUSEHOLD_STARTING_MONEY: 1000
HOUSEHOLD_STARTING_GOODS: 0
HOUSEHOLD_STARTING_STRATEGY: "god" 
# can be 
#   "god": pay nothing
#   "own house": pay utilities
#   "mortgage [A/B/C]": pay off the house according to the mortgage
#   "rent": pay rent by the rent inverval and cost

# Government

GOVERNMENT_STARTING_MONEY: 500